### ISSUE TITLE
Does it work with rails 3.1rc？

### ISSUE THREAD

**Issue by swachian** [ctran/annotate_models#28]
For the first time I use this gem. I find it work on a project with rails3.0, yet I fail to make it run with rails3.1. The rails version I use include 3.1.0.rc4 and 3.1.0.rc3.

The error I get is like: 

<pre>
ree-1.8.7-2011.03@r310/gems/activerecord-3.1.0.rc4/lib/active_record/railties/databases.rake:3: undefined method `namespace' for main:Object (NoMethodError)
.....

        from ./Rakefile:7
        from /.rvm/gems/ree-1.8.7-2011.03@r310/gems/annotate-2.4.0/lib/annotate.rb:17:in `load'
</pre>
