### ISSUE TITLE
Annotate stopped working with latest version 2.7.0 (Rails/active_record 4.1, pg 0.18.4), with following errors: 

### ISSUE THREAD

**Issue by MichalRemis** [ctran/annotate_models#316]
Unable to annotate app/models/packet.rb: undefined method `supports_foreign_keys?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0xda85f2c>
Unable to annotate app/models/triangle.rb: undefined method`supports_foreign_keys?' for #ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0xda85f2c
...

**Comment by QuintinAdam** [comment]
I also receive this error when I run `annotate -p bottom -k`. It works when I do not use the -k `annotate -p bottom`. 

Using the same setup as what was reported.

**Comment by brentwalther** [comment]
Fixed in pull request #347

**Comment by jacknoble** [comment]
Would it be possible to get a minor release with this fix?

**Comment by ctran** [comment]
Do you mean the head version on the "develop" branch or something else?

**Comment by jacknoble** [comment]
The head of 'develop' would be great.
